[astra]
requires-astra = ">=0.6.4"

[project]
name = "CameraTransform_K"
version = "0.1.0"
author = "Korarei"
requires-aviutl2 = "2005000"

[build]
[[build.plugins]]
id = "core"
shell = "pwsh"
variables = { SOURCE = "./modules" }

[build.plugins.release]
commands = '''
$dst = "$env:BUILD_DIRECTORY/Release"
cmake -S "$env:SOURCE" -B "$dst" --preset release -DREQUIRES_AVIUTL2="$env:PROJECT_REQUIRES_AVIUTL2" -DVERSION="$env:PROJECT_VERSION"
cp "$dst/compile_commands.json" "$env:SOURCE"
cmake --build "$dst"
'''
artifacts = ["${BUILD_DIRECTORY}/Release/*.mod2"]

[build.plugins.debug]
commands = '''
$dst = "$env:BUILD_DIRECTORY/Debug"
cmake -S "$env:SOURCE" -B "$dst" --preset debug -DREQUIRES_AVIUTL2="$env:PROJECT_REQUIRES_AVIUTL2"
cp "$dst/compile_commands.json" "$env:SOURCE"
cmake --build "$dst"
'''
artifacts = ["${BUILD_DIRECTORY}/Debug/*.mod2"]

[[build.scripts]]
id = "camera"
prefix = "@"
suffix = ".cam2"
variables = { SOURCE = "./scripts/camera", LABEL = "カメラ効果" }
sources = [
    { file = "${SOURCE}/transform.lua" },
    { file = "${SOURCE}/track.lua" },
    { file = "${SOURCE}/lens.lua" },
]

[[build.scripts]]
id = "fx"
prefix = "@"
suffix = ".anm2"
variables = { SOURCE = "./scripts/fx", LABEL = "配置" }
sources = [
    { file = "${SOURCE}/empty.lua" },
    { file = "${SOURCE}/relations.lua" },
]

[release]
[release.package]
information = "${PROJECT_NAME} v${PROJECT_VERSION} by ${PROJECT_AUTHOR}"
license = "MIT"
website = "https://github.com/korarei/AviUtl2_CameraTransform_K_Script"
report-issue = "https://github.com/korarei/AviUtl2_CameraTransform_K_Script/issues"
summary = "AviUtl ExEdit2 向けカメラ調整用ツール"
description = """
以下の機能が追加される

カメラ効果

- カメラ効果\\Transform@CameraTransform_K: カメラの位置や向きを調整
- カメラ効果\\Track@CameraTransform_K: ターゲットへカメラを追従
- カメラ効果\\Lens@CameraTransform_K: 見え方そのものを調整

アニメーション効果

- 配置\\Empty@CameraTransform_K: エフェクト版グループ制御
- 配置\\Relations@CameraTransform_K: 他オブジェクトと同期
"""

[[release.contents.extensions]]
directory = "Script/${PROJECT_NAME}"
files = ["plugin:core", "script:camera", "script:fx"]

[[release.contents.documents]]
directory = "Script/${PROJECT_NAME}"
files = ["./*.md", "./LICENSE"]
